controller_list:
  - name: fake_my_ur10_limited_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - robotiq_85_left_knuckle_joint
